/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figuras;

/**
 *
 * @author Stefany
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCirculo = new javax.swing.JLabel();
        lblCuadrado = new javax.swing.JLabel();
        lblTriangulo = new javax.swing.JLabel();
        lblRombo = new javax.swing.JLabel();
        lblTrapecio = new javax.swing.JLabel();
        lblRadio = new javax.swing.JLabel();
        lblAreaCirculo = new javax.swing.JLabel();
        lblPerimetroCirculo = new javax.swing.JLabel();
        txtLadoCuadrado = new javax.swing.JTextField();
        txtAreaCirculo = new javax.swing.JTextField();
        txtPerimetroCirculo = new javax.swing.JTextField();
        lblPerimetroCuadrado = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        txtAreaCuadrado = new javax.swing.JTextField();
        txtPerimetroCuadrado = new javax.swing.JTextField();
        lblLadoCuadrado = new javax.swing.JLabel();
        lblAreaCuadrado = new javax.swing.JLabel();
        lblPerimetroRombo = new javax.swing.JLabel();
        txtDiagInf = new javax.swing.JTextField();
        txtAreaRombo = new javax.swing.JTextField();
        txtPerimetroRombo = new javax.swing.JTextField();
        lblDiagInf = new javax.swing.JLabel();
        lblAreaRombo = new javax.swing.JLabel();
        txtDiagSup = new javax.swing.JTextField();
        lblDiagSup = new javax.swing.JLabel();
        lblRectangulo = new javax.swing.JLabel();
        txtBaseTriangulo = new javax.swing.JTextField();
        txtAreaTriangulo = new javax.swing.JTextField();
        txtPerimetroTriangulo = new javax.swing.JTextField();
        lblBaseTriangulo = new javax.swing.JLabel();
        lblAreaTriangulo = new javax.swing.JLabel();
        txtAlturaTriangulo = new javax.swing.JTextField();
        lblAlturaTriangulo = new javax.swing.JLabel();
        lblPerimetroTriangulo = new javax.swing.JLabel();
        txtHipotenusa = new javax.swing.JTextField();
        txtTipoTriangulo = new javax.swing.JTextField();
        lblHipotenusa = new javax.swing.JLabel();
        lblTipoTriangulo = new javax.swing.JLabel();
        txtBaseRectangulo = new javax.swing.JTextField();
        txtAreaRectangulo = new javax.swing.JTextField();
        txtPerimetroRectangulo = new javax.swing.JTextField();
        lblBaseRectangulo = new javax.swing.JLabel();
        lblAreaRectangulo = new javax.swing.JLabel();
        txtAlturaRectangulo = new javax.swing.JTextField();
        lblAlturaRectangulo = new javax.swing.JLabel();
        lblPerimetroRectangulo = new javax.swing.JLabel();
        txtBaseMenor = new javax.swing.JTextField();
        txtAlturaTrapecio = new javax.swing.JTextField();
        txtLado1 = new javax.swing.JTextField();
        lblLado2 = new javax.swing.JLabel();
        lblAlturaTrapecio = new javax.swing.JLabel();
        txtBaseMayor = new javax.swing.JTextField();
        lblBaseMayor = new javax.swing.JLabel();
        lblLado1 = new javax.swing.JLabel();
        txtLado2 = new javax.swing.JTextField();
        txtAreaTrapecio = new javax.swing.JTextField();
        lblBaseMenor = new javax.swing.JLabel();
        lblAreaTrapecio = new javax.swing.JLabel();
        lblPerimetroTrapecio = new javax.swing.JLabel();
        txtPerimetroTrapecio = new javax.swing.JTextField();
        btnCalcularCirculo = new javax.swing.JButton();
        btnBorrarCirculo = new javax.swing.JButton();
        btnCalcularCuadrado = new javax.swing.JButton();
        btnBorrarCuadrado = new javax.swing.JButton();
        btnCalcularRombo = new javax.swing.JButton();
        btnBorrarRombo = new javax.swing.JButton();
        btnCalcularTriangulo = new javax.swing.JButton();
        btnBorrarTriangulo = new javax.swing.JButton();
        btnBorrarTrapecio = new javax.swing.JButton();
        btnCalcularTrapecio = new javax.swing.JButton();
        btnBorrarRectangulo = new javax.swing.JButton();
        btnCalcularRectangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Figuras Geométricas");

        lblCirculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCirculo.setText("Círculo");

        lblCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCuadrado.setText("Cuadrado");

        lblTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTriangulo.setText("Triángulo");

        lblRombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRombo.setText("Rombo");

        lblTrapecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrapecio.setText("Trapecio");

        lblRadio.setText("Valor del radio");

        lblAreaCirculo.setText("Área");

        lblPerimetroCirculo.setText("Perímetro");

        txtLadoCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadoCuadradoActionPerformed(evt);
            }
        });

        txtAreaCirculo.setEditable(false);
        txtAreaCirculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaCirculoActionPerformed(evt);
            }
        });

        txtPerimetroCirculo.setEditable(false);
        txtPerimetroCirculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblPerimetroCuadrado.setText("Perímetro");

        txtRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioActionPerformed(evt);
            }
        });

        txtAreaCuadrado.setEditable(false);
        txtAreaCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaCuadradoActionPerformed(evt);
            }
        });

        txtPerimetroCuadrado.setEditable(false);
        txtPerimetroCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblLadoCuadrado.setText("Valor del lado");

        lblAreaCuadrado.setText("Área");

        lblPerimetroRombo.setText("Perímetro");

        txtDiagInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagInfActionPerformed(evt);
            }
        });

        txtAreaRombo.setEditable(false);
        txtAreaRombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAreaRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaRomboActionPerformed(evt);
            }
        });

        txtPerimetroRombo.setEditable(false);
        txtPerimetroRombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDiagInf.setText("Diag. Inferior");

        lblAreaRombo.setText("Área");

        txtDiagSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagSupActionPerformed(evt);
            }
        });

        lblDiagSup.setText("Diag. Superior");

        lblRectangulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRectangulo.setText("Rectángulo");

        txtBaseTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseTrianguloActionPerformed(evt);
            }
        });

        txtAreaTriangulo.setEditable(false);
        txtAreaTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaTrianguloActionPerformed(evt);
            }
        });

        txtPerimetroTriangulo.setEditable(false);
        txtPerimetroTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblBaseTriangulo.setText("Base");

        lblAreaTriangulo.setText("Área");

        txtAlturaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaTrianguloActionPerformed(evt);
            }
        });

        lblAlturaTriangulo.setText("Altura");

        lblPerimetroTriangulo.setText("Perímetro");

        txtHipotenusa.setEditable(false);
        txtHipotenusa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHipotenusaActionPerformed(evt);
            }
        });

        txtTipoTriangulo.setEditable(false);
        txtTipoTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblHipotenusa.setText("Hipotenusa");

        lblTipoTriangulo.setText("Tipo de Triángulo");

        txtBaseRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseRectanguloActionPerformed(evt);
            }
        });

        txtAreaRectangulo.setEditable(false);
        txtAreaRectangulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaRectanguloActionPerformed(evt);
            }
        });

        txtPerimetroRectangulo.setEditable(false);
        txtPerimetroRectangulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblBaseRectangulo.setText("Base");

        lblAreaRectangulo.setText("Área");

        txtAlturaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaRectanguloActionPerformed(evt);
            }
        });

        lblAlturaRectangulo.setText("Altura");

        lblPerimetroRectangulo.setText("Perímetro");

        txtBaseMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseMenorActionPerformed(evt);
            }
        });

        txtAlturaTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaTrapecioActionPerformed(evt);
            }
        });

        lblLado2.setText("Lado 2");

        lblAlturaTrapecio.setText("Altura");

        txtBaseMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseMayorActionPerformed(evt);
            }
        });

        lblBaseMayor.setText("Base Mayor");

        lblLado1.setText("Lado 1");

        txtLado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLado2ActionPerformed(evt);
            }
        });

        txtAreaTrapecio.setEditable(false);
        txtAreaTrapecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblBaseMenor.setText("Base Menor");

        lblAreaTrapecio.setText("Área");

        lblPerimetroTrapecio.setText("Perímetro");

        txtPerimetroTrapecio.setEditable(false);
        txtPerimetroTrapecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnCalcularCirculo.setText("Calcular");
        btnCalcularCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCirculoActionPerformed(evt);
            }
        });

        btnBorrarCirculo.setText("Borrar");
        btnBorrarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCirculoActionPerformed(evt);
            }
        });

        btnCalcularCuadrado.setText("Calcular");
        btnCalcularCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCuadradoActionPerformed(evt);
            }
        });

        btnBorrarCuadrado.setText("Borrar");
        btnBorrarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuadradoActionPerformed(evt);
            }
        });

        btnCalcularRombo.setText("Calcular");
        btnCalcularRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRomboActionPerformed(evt);
            }
        });

        btnBorrarRombo.setText("Borrar");
        btnBorrarRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRomboActionPerformed(evt);
            }
        });

        btnCalcularTriangulo.setText("Calcular");
        btnCalcularTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTrianguloActionPerformed(evt);
            }
        });

        btnBorrarTriangulo.setText("Borrar");
        btnBorrarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTrianguloActionPerformed(evt);
            }
        });

        btnBorrarTrapecio.setText("Borrar");
        btnBorrarTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTrapecioActionPerformed(evt);
            }
        });

        btnCalcularTrapecio.setText("Calcular");
        btnCalcularTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTrapecioActionPerformed(evt);
            }
        });

        btnBorrarRectangulo.setText("Borrar");
        btnBorrarRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRectanguloActionPerformed(evt);
            }
        });

        btnCalcularRectangulo.setText("Calcular");
        btnCalcularRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTriangulo)
                                    .addGap(203, 203, 203))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblHipotenusa)
                                            .addGap(44, 44, 44))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(lblPerimetroTriangulo)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblBaseTriangulo)
                                                        .addGap(28, 28, 28)))
                                                .addComponent(lblAreaTriangulo)
                                                .addComponent(lblAlturaTriangulo)
                                                .addComponent(lblTipoTriangulo))
                                            .addGap(13, 13, 13)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAlturaTriangulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtBaseTriangulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtAreaTriangulo)
                                                .addComponent(txtPerimetroTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAreaCirculo)
                                            .addComponent(lblPerimetroCirculo))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAreaCirculo)
                                            .addComponent(txtPerimetroCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCirculo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCalcularTriangulo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBorrarTriangulo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCalcularCirculo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBorrarCirculo)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrapecio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLado2)
                                            .addComponent(lblAlturaTrapecio)
                                            .addComponent(lblBaseMayor)
                                            .addComponent(lblLado1)
                                            .addComponent(lblBaseMenor)
                                            .addComponent(lblPerimetroTrapecio)
                                            .addComponent(lblAreaTrapecio))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtBaseMayor, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtBaseMenor, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtAlturaTrapecio)
                                                    .addComponent(txtLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAreaTrapecio)
                                                .addComponent(txtLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPerimetroTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRectangulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblPerimetroRectangulo)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblBaseRectangulo)
                                                    .addGap(28, 28, 28)))
                                            .addComponent(lblAreaRectangulo)
                                            .addComponent(lblAlturaRectangulo))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAreaRectangulo)
                                            .addComponent(txtPerimetroRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(txtBaseRectangulo)
                                            .addComponent(txtAlturaRectangulo)))))
                            .addComponent(lblCuadrado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLadoCuadrado)
                                            .addComponent(lblAreaCuadrado)
                                            .addComponent(lblPerimetroCuadrado))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAreaCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(txtPerimetroCuadrado)
                                            .addComponent(txtLadoCuadrado)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnCalcularCuadrado)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBorrarCuadrado)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDiagSup)
                                            .addComponent(lblDiagInf)
                                            .addComponent(lblAreaRombo)
                                            .addComponent(lblPerimetroRombo)
                                            .addComponent(lblRombo))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDiagSup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAreaRombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiagInf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPerimetroRombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCalcularRectangulo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBorrarRectangulo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCalcularRombo)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBorrarRombo)))
                                        .addGap(13, 13, 13))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(btnCalcularTrapecio)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarTrapecio)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCirculo)
                            .addComponent(lblCuadrado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRadio)
                                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAreaCirculo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPerimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimetroCirculo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCalcularCirculo)
                                    .addComponent(btnBorrarCirculo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiagInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiagSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiagSup))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAreaRombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAreaRombo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPerimetroRombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimetroRombo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRombo)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiagInf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLadoCuadrado)
                            .addComponent(txtLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAreaCuadrado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPerimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerimetroCuadrado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcularCuadrado)
                            .addComponent(btnBorrarCuadrado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularRombo)
                    .addComponent(btnBorrarRombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTrapecio)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBaseMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBaseMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBaseMayor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAlturaTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlturaTrapecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lblLado1))
                            .addComponent(lblBaseMenor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLado2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAreaTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAreaTrapecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerimetroTrapecio)
                            .addComponent(txtPerimetroTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTriangulo)
                            .addComponent(lblRectangulo))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBaseTriangulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBaseTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAlturaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAlturaTriangulo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAreaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAreaTriangulo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPerimetroTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPerimetroTriangulo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAlturaRectangulo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAreaRectangulo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPerimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPerimetroRectangulo)))
                                    .addComponent(lblBaseRectangulo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHipotenusa)
                                            .addComponent(txtHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTipoTriangulo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnCalcularRectangulo)
                                            .addComponent(btnBorrarRectangulo))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcularTriangulo)
                            .addComponent(btnBorrarTriangulo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularTrapecio)
                    .addComponent(btnBorrarTrapecio))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLadoCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadoCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadoCuadradoActionPerformed

    private void txtAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaCirculoActionPerformed

    private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadioActionPerformed

    private void txtAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaCuadradoActionPerformed

    private void txtDiagInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagInfActionPerformed

    private void txtAreaRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaRomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaRomboActionPerformed

    private void txtDiagSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagSupActionPerformed

    private void txtBaseTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseTrianguloActionPerformed

    private void txtAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTrianguloActionPerformed

    private void txtAlturaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaTrianguloActionPerformed

    private void txtHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHipotenusaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHipotenusaActionPerformed

    private void txtBaseRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseRectanguloActionPerformed

    private void txtAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaRectanguloActionPerformed

    private void txtAlturaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaRectanguloActionPerformed

    private void txtBaseMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseMenorActionPerformed

    private void txtAlturaTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaTrapecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaTrapecioActionPerformed

    private void txtBaseMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseMayorActionPerformed

    private void txtLado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLado2ActionPerformed

    private void btnCalcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCirculoActionPerformed

        double radio = Double.parseDouble(txtRadio.getText());
        txtAreaCirculo.setText("" + Math.round(Math.PI * Math.pow(radio, 2)));
        txtPerimetroCirculo.setText("" + Math.round(2 * Math.PI * radio));

    }//GEN-LAST:event_btnCalcularCirculoActionPerformed

    private void btnBorrarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCirculoActionPerformed
        txtRadio.setText("");
        txtAreaCirculo.setText("");
        txtPerimetroCirculo.setText("");
    }//GEN-LAST:event_btnBorrarCirculoActionPerformed

    private void btnCalcularCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCuadradoActionPerformed
        double lado = Double.parseDouble(txtLadoCuadrado.getText());
        txtAreaCuadrado.setText("" + lado * lado);
        txtPerimetroCuadrado.setText("" + 4 * lado);
    }//GEN-LAST:event_btnCalcularCuadradoActionPerformed

    private void btnBorrarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuadradoActionPerformed
        txtLadoCuadrado.setText("");
        txtAreaCuadrado.setText("");
        txtPerimetroCuadrado.setText("");
    }//GEN-LAST:event_btnBorrarCuadradoActionPerformed

    private void btnCalcularRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRomboActionPerformed
        double diagonal_sup = Double.parseDouble(txtDiagSup.getText());
        double diagonal_inf = Double.parseDouble(txtDiagInf.getText());
        txtAreaRombo.setText("" + (diagonal_sup * diagonal_inf) / 2);
        txtPerimetroRombo.setText("" + Math.round(4 * Math.pow((diagonal_sup * diagonal_sup) / 4 + (diagonal_inf * diagonal_inf) / 4, 0.5)));
    }//GEN-LAST:event_btnCalcularRomboActionPerformed

    private void btnBorrarRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRomboActionPerformed
        txtDiagSup.setText("");
        txtDiagInf.setText("");
        txtAreaRombo.setText("");
        txtPerimetroRombo.setText("");
    }//GEN-LAST:event_btnBorrarRomboActionPerformed

    private void btnCalcularTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTrianguloActionPerformed
        double base = Double.parseDouble(txtBaseTriangulo.getText());
        double altura = Double.parseDouble(txtAlturaTriangulo.getText());
        double hipotenusa = Math.round(Math.pow(base * base + altura * altura, 0.5));

        txtAreaTriangulo.setText("" + Math.round((base * altura / 2)));
        txtPerimetroTriangulo.setText("" + (base + altura + hipotenusa));
        txtHipotenusa.setText("" + hipotenusa);

        if ((base == altura) && (base == hipotenusa) && (altura == hipotenusa)) {
            txtTipoTriangulo.setText("Triángulo equilatero");
        } else if ((base != altura) && (base != hipotenusa) && (altura != hipotenusa)) {
            txtTipoTriangulo.setText("Triángulo escaleno");
        } else {
            txtTipoTriangulo.setText("Triángulo isosceles");
        }
    }//GEN-LAST:event_btnCalcularTrianguloActionPerformed

    private void btnBorrarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTrianguloActionPerformed
        txtBaseTriangulo.setText("");
        txtAlturaTriangulo.setText("");
        txtAreaTriangulo.setText("");
        txtPerimetroTriangulo.setText("");
        txtHipotenusa.setText("");
        txtTipoTriangulo.setText("");
    }//GEN-LAST:event_btnBorrarTrianguloActionPerformed

    private void btnBorrarTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTrapecioActionPerformed
        txtBaseMenor.setText("");
        txtBaseMayor.setText("");
        txtAlturaTrapecio.setText("");
        txtLado1.setText("");
        txtLado2.setText("");
        txtAreaTrapecio.setText("");
        txtPerimetroTrapecio.setText("");
    }//GEN-LAST:event_btnBorrarTrapecioActionPerformed

    private void btnCalcularTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTrapecioActionPerformed

        double base_menor = Double.parseDouble(txtBaseMenor.getText());
        double base_mayor = Double.parseDouble(txtBaseMayor.getText());
        double altura = Double.parseDouble(txtAlturaTrapecio.getText());
        double lado1 = Double.parseDouble(txtLado1.getText());
        double lado2 = Double.parseDouble(txtLado2.getText());

        txtAreaTrapecio.setText("" + ((base_menor + base_mayor) / 2) * altura);
        txtPerimetroTrapecio.setText("" + (base_menor + base_mayor + lado1 + lado2));
    }//GEN-LAST:event_btnCalcularTrapecioActionPerformed

    private void btnBorrarRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRectanguloActionPerformed
        txtBaseRectangulo.setText("");
        txtAlturaRectangulo.setText("");
        txtAreaRectangulo.setText("");
        txtPerimetroRectangulo.setText("");
    }//GEN-LAST:event_btnBorrarRectanguloActionPerformed

    private void btnCalcularRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRectanguloActionPerformed
        double base = Double.parseDouble(txtBaseRectangulo.getText());
        double altura = Double.parseDouble(txtAlturaRectangulo.getText());

        txtAreaRectangulo.setText("" + (base * altura));
        txtPerimetroRectangulo.setText("" + ((2 * base) + (2 * altura)));
    }//GEN-LAST:event_btnCalcularRectanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarCirculo;
    private javax.swing.JButton btnBorrarCuadrado;
    private javax.swing.JButton btnBorrarRectangulo;
    private javax.swing.JButton btnBorrarRombo;
    private javax.swing.JButton btnBorrarTrapecio;
    private javax.swing.JButton btnBorrarTriangulo;
    private javax.swing.JButton btnCalcularCirculo;
    private javax.swing.JButton btnCalcularCuadrado;
    private javax.swing.JButton btnCalcularRectangulo;
    private javax.swing.JButton btnCalcularRombo;
    private javax.swing.JButton btnCalcularTrapecio;
    private javax.swing.JButton btnCalcularTriangulo;
    private javax.swing.JLabel lblAlturaRectangulo;
    private javax.swing.JLabel lblAlturaTrapecio;
    private javax.swing.JLabel lblAlturaTriangulo;
    private javax.swing.JLabel lblAreaCirculo;
    private javax.swing.JLabel lblAreaCuadrado;
    private javax.swing.JLabel lblAreaRectangulo;
    private javax.swing.JLabel lblAreaRombo;
    private javax.swing.JLabel lblAreaTrapecio;
    private javax.swing.JLabel lblAreaTriangulo;
    private javax.swing.JLabel lblBaseMayor;
    private javax.swing.JLabel lblBaseMenor;
    private javax.swing.JLabel lblBaseRectangulo;
    private javax.swing.JLabel lblBaseTriangulo;
    private javax.swing.JLabel lblCirculo;
    private javax.swing.JLabel lblCuadrado;
    private javax.swing.JLabel lblDiagInf;
    private javax.swing.JLabel lblDiagSup;
    private javax.swing.JLabel lblHipotenusa;
    private javax.swing.JLabel lblLado1;
    private javax.swing.JLabel lblLado2;
    private javax.swing.JLabel lblLadoCuadrado;
    private javax.swing.JLabel lblPerimetroCirculo;
    private javax.swing.JLabel lblPerimetroCuadrado;
    private javax.swing.JLabel lblPerimetroRectangulo;
    private javax.swing.JLabel lblPerimetroRombo;
    private javax.swing.JLabel lblPerimetroTrapecio;
    private javax.swing.JLabel lblPerimetroTriangulo;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JLabel lblRectangulo;
    private javax.swing.JLabel lblRombo;
    private javax.swing.JLabel lblTipoTriangulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTrapecio;
    private javax.swing.JLabel lblTriangulo;
    private javax.swing.JTextField txtAlturaRectangulo;
    private javax.swing.JTextField txtAlturaTrapecio;
    private javax.swing.JTextField txtAlturaTriangulo;
    private javax.swing.JTextField txtAreaCirculo;
    private javax.swing.JTextField txtAreaCuadrado;
    private javax.swing.JTextField txtAreaRectangulo;
    private javax.swing.JTextField txtAreaRombo;
    private javax.swing.JTextField txtAreaTrapecio;
    private javax.swing.JTextField txtAreaTriangulo;
    private javax.swing.JTextField txtBaseMayor;
    private javax.swing.JTextField txtBaseMenor;
    private javax.swing.JTextField txtBaseRectangulo;
    private javax.swing.JTextField txtBaseTriangulo;
    private javax.swing.JTextField txtDiagInf;
    private javax.swing.JTextField txtDiagSup;
    private javax.swing.JTextField txtHipotenusa;
    private javax.swing.JTextField txtLado1;
    private javax.swing.JTextField txtLado2;
    private javax.swing.JTextField txtLadoCuadrado;
    private javax.swing.JTextField txtPerimetroCirculo;
    private javax.swing.JTextField txtPerimetroCuadrado;
    private javax.swing.JTextField txtPerimetroRectangulo;
    private javax.swing.JTextField txtPerimetroRombo;
    private javax.swing.JTextField txtPerimetroTrapecio;
    private javax.swing.JTextField txtPerimetroTriangulo;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtTipoTriangulo;
    // End of variables declaration//GEN-END:variables

}
